# SPDX-FileCopyrightText: 2025 Supabase <support@supabase.io>
# SPDX-FileCopyrightText: 2025 ≈Åukasz Niemier <~@hauleth.dev>
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: EUPL-1.2

version: "3"

services:
  db:
    image: postgres:18.2
    container_name: ultravisor-db
    ports:
      - "6432:5432"
    volumes:
      - ./dev/postgres:/docker-entrypoint-initdb.d/
      # Uncomment to set MD5 authentication method on uninitialized databases
      # - ./dev/postgres/md5/etc/postgresql/pg_hba.conf:/etc/postgresql/pg_hba.conf
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf -c max_prepared_transactions=2000
    environment:
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_PASSWORD: postgres
      # Uncomment to set MD5 authentication method on uninitialized databases
      # POSTGRES_INITDB_ARGS: --auth-host=md5
