# SPDX-FileCopyrightText: 2025 Supabase <support@supabase.io>
# SPDX-FileCopyrightText: 2025 ≈Åukasz Niemier <~@hauleth.dev>
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: EUPL-1.2

site_name: ultravisor
site_url: https://ultravisor.github.io/ultravisor
site_description: A cloud native multi-tenant connection pooler for Postgres

repo_name: ultravisor/ultravisor
repo_url: https://github.com/ultravisor/ultravisor

nav:
  - Welcome: "index.md"
  - FAQ: "faq.md"
  - Development:
      - Installation: "development/installation.md"
      - Setup: "development/setup.md"
      - Docs: "development/docs.md"
  - Deployment:
      - Deploy with Fly.io: "deployment/fly.md"
  - Connecting:
      - Overview: "connecting/overview.md"
      - Authentication: "connecting/authentication.md"
  - Configuration:
      - Tenants: "configuration/tenants.md"
      - Users: "configuration/users.md"
      - Pool Modes: "configuration/pool_modes.md"
  - Migrating:
      - from PgBouncer: "migrating/pgbouncer.md"
  - Monitoring:
      - Metrics: "monitoring/metrics.md"
      - Logs: "monitoring/logs.md"
  - ORMs:
      - Prisma: "orms/prisma.md"

theme:
  name: "material"
  favicon: "images/favicon.ico"
  logo: "images/favicon.ico"
  homepage: https://ultravisor.github.io/ultravisor
  features:
    - navigation.expand
  palette:
    primary: black
    accent: light green

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      guess_lang: false
      use_pygments: true
      pygments_style: default
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.tasklist
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
